optimized

diff --git a/rumiai-os b/rumiai-os
--- a/rumiai-os
+++ b/rumiai-os
@@ -18,17 +18,17 @@ RumiAI_fatal()
 # RumiAI_path_canonicalize_existing <path>
 # returns a canonicalized version of <path>, return error if does not exist
 RumiAI_path_canonicalize_existing()
-{
-  if [ ! "$#" -eq 1 ] || [ ! -e "$1" ] || ! set -- "$(command -p -- realpath -- "$1" 2>/dev/null)x"
+(
+  if [ ! "$#" -eq 1 ] || [ ! -e "$1" ] || ! rp="$(command -p -- realpath -- "$1" 2>/dev/null)x"
   then
     return 1
   fi
 
-  set -- "${1%x}"
+  set -- "${rp%x}"
 
-  [ -e "$1" ] || return 1
-  printf -- '%s\n' "$1"
-}
+  [ -e "$rp" ] || return 1
+  printf -- '%s\n' "$rp"
+)
 
 #-------------------------------------------------------------------------------
 # ROOT RESOLUTION
@@ -88,18 +88,103 @@ readonly -- \
 # TEXT
 #-------------------------------------------------------------------------------
 
-# load lib
-command -- . "$RumiAI_LIB_DIR/text.lib" || RumiAI_fatal 'RumiAI_BOOTSTRAP_FATAL_TEXT_LOAD_ERROR'
+# functions
+RumiAI_is_integer()
+{
+  [ "$#" -eq 1 ] || return 1
+
+  case "$1" in *[!0-9]* | "") return 2;; *) return 0;; esac
+}
+
+RumiAI_text_safe_id()
+{
+  [ "$#" -eq 1 ] || return 1
+
+  case "$1" in
+    # first character match
+    [a-z0-9]*)
+      # middle characters and final character exclusions
+      case $1 in
+        *[!a-z0-9._-]* | *[._-])
+          return 1
+          ;;
+      esac
+      ;;
+    *)
+      return 1
+      ;;
+  esac
+
+  return 0
+}
+
+RumiAI_text_safe_id_case()
+{
+  [ "$#" -eq 1 ] || return 1
+
+  case "$1" in
+    # first character match
+    [A-Za-z0-9]*)
+      # middle characters and final character exclusions
+      case $1 in
+        *[!A-Za-z0-9._-]* | *[._-])
+          return 1
+          ;;
+      esac
+      ;;
+    *)
+      return 1
+      ;;
+  esac
+
+  return 0
+}
 
 #-------------------------------------------------------------------------------
 # LANG
 #-------------------------------------------------------------------------------
 
-# load lib
-command -- . "$RumiAI_LIB_DIR/lang.lib" || RumiAI_fatal 'RumiAI_BOOTSTRAP_FATAL_LANG_LOAD_ERROR'
+# functions
+lang()
+(
+  [ "$#" -eq 2 ] || return 1
 
-# init
-RumiAI_lang_init
+  RumiAI_lang_domain=$1
+  RumiAI_lang_message_id=$2
+
+  case "$RumiAI_LANGUAGE" in [a-z][a-z]_[A-Z][A-Z]) true;; *) false;; esac && RumiAI_text_safe_id "$RumiAI_lang_domain" && RumiAI_text_safe_id "$RumiAI_lang_message_id" || return 2
+
+  RumiAI_lang_message="$(command -p -- cat "$RumiAI_LANG_DIR/$RumiAI_LANGUAGE/$RumiAI_lang_domain/$RumiAI_lang_message_id" 2>/dev/null)"
+  if [ "$?" != 0 ]
+  then
+    [ "$RumiAI_LANGUAGE" != "$RumiAI_LANGUAGE_FALLBACK" ] && case "$RumiAI_LANGUAGE_FALLBACK" in [a-z][a-z]_[A-Z][A-Z]) true;; *) false;; esac && RumiAI_lang_message="$(command -p -- cat "$RumiAI_LANG_DIR/$RumiAI_LANGUAGE_FALLBACK/$RumiAI_lang_domain/$RumiAI_lang_message_id" 2>/dev/null)"
+    if [ "$?" != 0 ]
+    then
+      RumiAI_lang_message="${RumiAI_lang_domain}.${RumiAI_lang_message_id}"
+    fi
+  fi
+
+  printf -- '%s\n' "$RumiAI_lang_message"
+)
+
+# conf files
+RumiAI_CONF_FILE_LANG_LANGUAGE=$RumiAI_CONF_DIR/lang/language
+
+# set var - language
+RumiAI_LANGUAGE_FALLBACK=en_US
+
+if ! RumiAI_LANGUAGE="$(command -p -- cat "$RumiAI_CONF_FILE_LANG_LANGUAGE" 2>/dev/null)" || [ -z "$RumiAI_LANGUAGE" ] || case "$RumiAI_LANGUAGE" in [a-z][a-z]_[A-Z][A-Z]) false ;; *) true;; esac && [ ! -d "$RumiAI_LANG_DIR/$RumiAI_LANGUAGE" ]
+then
+  printf -- '%s\n' 'RumiAI_BOOTSTRAP_ERROR_LANG_LANGUAGE_LOAD_ERROR' >&2
+
+  RumiAI_LANGUAGE="$RumiAI_LANGUAGE_FALLBACK"
+fi
+
+# set var - text encoding
+RumiAI_TEXT_ENCODING=UTF-8
+
+# unset variables
+unset -v -- RumiAI_CONF_FILE_LANG_LANGUAGE
 
 # export variables
 export -- RumiAI_LANGUAGE RumiAI_LANGUAGE_FALLBACK RumiAI_TEXT_ENCODING
@@ -108,8 +193,123 @@ export -- RumiAI_LANGUAGE RumiAI_LANGUAGE_FALLBACK RumiAI_TEXT_ENCODING
 # LOGGER
 #-------------------------------------------------------------------------------
 
-# load lib
-command -- . "$RumiAI_LIB_DIR/log.lib" || RumiAI_fatal 'RumiAI_BOOTSTRAP_FATAL_LOG_LOAD_ERROR'
+: "${RumiAI_LOG_LEVEL:=info}"
+
+RumiAI_log_fields_valid()
+(
+  [ "$(( $# % 2 ))" -eq 0 ] || return 1
+
+  while [ "$#" -gt 0 ]
+  do
+    RumiAI_text_safe_id "$1" || return 1
+    shift 2
+  done
+
+  return 0
+)
+
+log()
+(
+  [ "$#" -ge 3 ] || return 1
+
+  RumiAI_log_severity="$1"
+  shift
+
+  case "$RumiAI_log_severity" in
+    fatal)
+      RumiAI_log_priority=1
+      ;;
+    error)
+      RumiAI_log_priority=2
+      ;;
+    warn)
+      RumiAI_log_priority=3
+      ;;
+    info)
+      RumiAI_log_priority=4
+      ;;
+    debug)
+      RumiAI_log_priority=5
+      ;;
+    trace)
+      RumiAI_log_priority=6
+      ;;
+    *)
+      return 2
+      ;;
+  esac
+
+  case "$RumiAI_LOG_LEVEL" in
+    off | none)
+      RumiAI_log_threshold="0"
+      ;;
+    fatal)
+      RumiAI_log_threshold="1"
+      ;;
+    error)
+      RumiAI_log_threshold="2"
+      ;;
+    warn)
+      RumiAI_log_threshold="3"
+      ;;
+    info)
+      RumiAI_log_threshold="4"
+      ;;
+    debug)
+      RumiAI_log_threshold="5"
+      ;;
+    trace | all)
+      RumiAI_log_threshold="6"
+      ;;
+    *)
+      return 6
+      ;;
+  esac
+
+  [ "$RumiAI_log_priority" -le "$RumiAI_log_threshold" ] || return 0
+
+  RumiAI_log_domain=$1
+  RumiAI_log_message_id=$2
+  shift 2
+
+  RumiAI_text_safe_id "$RumiAI_log_domain" || \
+    return 3
+
+  RumiAI_text_safe_id "$RumiAI_log_message_id" || \
+    return 4
+
+  RumiAI_log_fields_valid "$@" || return 5
+
+  if ! RumiAI_log_message=$(lang "$RumiAI_log_domain" "$RumiAI_log_message_id")
+  then
+    RumiAI_log_message=$RumiAI_log_domain.$RumiAI_log_message_id
+  fi
+
+  if ! RumiAI_log_timestamp=$(command -p -- date '+%Y-%m-%dT%H:%M:%S' 2>/dev/null)
+  then
+    RumiAI_log_timestamp=-
+  fi
+
+  printf -- '[%s] [%s] [%s.%s] %s' \
+    "$RumiAI_log_timestamp" \
+    "$RumiAI_log_severity" \
+    "$RumiAI_log_domain" \
+    "$RumiAI_log_message_id" \
+    "$RumiAI_log_message" >&2
+
+  while [ "$#" -gt 0 ]
+  do
+    RumiAI_log_field_name=$1
+    RumiAI_log_field_value=$2
+    shift 2
+
+    printf -- ' [%s="%s"]' \
+      "$RumiAI_log_field_name" \
+      "$RumiAI_log_field_value" >&2
+  done
+
+  printf -- '\n' >&2
+)
 
 #-------------------------------------------------------------------------------
 # OSARCH DETECTION
@@ -162,35 +362,6 @@ readonly -- \
   RumiAI_OSARCH_BIN_DIR
 
 #-------------------------------------------------------------------------------
-# SHELL
-#-------------------------------------------------------------------------------
-
-# conf files
-RumiAI_CONF_FILE_SHELL_DEFAULT=$RumiAI_CONF_DIR/shell/default
-
-# set var - shell
-# if ! IFS= read -r RumiAI_SHELL < "$RumiAI_CONF_FILE_SHELL_DEFAULT"
-if ! RumiAI_SHELL="$(command -p -- cat "$RumiAI_CONF_FILE_SHELL_DEFAULT" 2>/dev/null)"
-then
-  printf -- '%s\n' 'RumiAI_BOOTSTRAP_ERROR_SHELL_DEFAULT_LOAD_ERROR' >&2
-  RumiAI_SHELL=sh
-fi
-
-if ! command -v -- "$RumiAI_SHELL" >/dev/null 2>&1
-then
-  printf -- '%s\n' 'RumiAI_BOOTSTRAP_ERROR_SHELL_DEFAULT_LOAD_ERROR' >&2
-  RumiAI_SHELL=sh
-fi
-
-# unset variables
-unset -v -- RumiAI_CONF_FILE_SHELL_DEFAULT
-
-# export variables
-export -- RumiAI_SHELL
-
-readonly -- RumiAI_SHELL
-
-#-------------------------------------------------------------------------------
 # EXECUTE
 #-------------------------------------------------------------------------------
 
@@ -200,7 +371,7 @@ RumiAI_FATAL_EXIT_CODE="$RumiAI_FATAL_EXIT_CODE_EXECUTION"
 # execute shell
 if [ "$#" -eq 0 ]
 then
-  : "${SHELL:-sh}"
+  : "${SHELL:=sh}"
   printf -- '%s\n'  "$(tput setaf 2)$(tput bold)${SHELL} $(tput setaf 7)RumiAI$(tput sgr0)" >&2
   exec "${SHELL}"
 fi
