optimize

diff --git a/rumiai-os b/rumiai-os
--- a/rumiai-os
+++ b/rumiai-os
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 #-------------------------------------------------------------------------------
-# FATAL ERROR FUNCTION
+# FUNCTIONS
 #-------------------------------------------------------------------------------
 
 fatal()
 {
-  case "$1" in *[!0-9]* | "") EXIT_CODE="1";; *) EXIT_CODE="$1"; shift;; esac
+  case "$1" in *[!0-9]* | "") EXIT_CODE="1";; *) EXIT_CODE="$1"; shift; [ "$EXIT_CODE" -gt "255" ] && EXIT_CODE="1";; esac
 
   if [ "$#" -gt "0" ]
   then
@@ -22,8 +22,6 @@ fatal()
   exit "$EXIT_CODE"
 }
 
-#-------------------------------------------------------------------------------
-# CANONICALIZE EXISTING PATH FUNCTION
 #-------------------------------------------------------------------------------
 
 readpathce()
@@ -58,72 +56,8 @@ x}"
 
   eval $1='$2'
 }
-
-#-------------------------------------------------------------------------------
-# ROOT RESOLUTION
 #-------------------------------------------------------------------------------
 
-# canonicalize the path of this script and check that it is really a file
-readpathce "m_BOOTSTRAP_BIN" "$0" && [ -f "$m_BOOTSTRAP_BIN" ] || fatal 'bootstrap bin resolution error'
-
-# extract root
-m_ROOT=${m_BOOTSTRAP_BIN%/*}
-[ -n "$m_ROOT" ] || m_ROOT=/
-
-# check can cd into it
-(cd -- "$m_ROOT" 2>/dev/null) || fatal 'bootstrap dir error'
-
-# export root
-export -- m_BOOTSTRAP_BIN m_ROOT
-
-readonly -- m_BOOTSTRAP_BIN m_ROOT
-
-#-------------------------------------------------------------------------------
-# FUNDAMENTAL SYSTEM DIRECTORIES
-#-------------------------------------------------------------------------------
-
-# set values
-m_BIN_DIR=$m_ROOT/bin
-m_BIN_SYS_DIR=$m_BIN_DIR/sys
-m_BIN_SYS_OSARCH_DIR=$m_BIN_DIR/sys-osarch
-m_BIN_EXT_DIR=$m_ROOT/bin/ext
-m_BIN_EXT_OSARCH_DIR=$m_ROOT/bin/ext-osarch
-m_LIB_DIR=$m_ROOT/lib
-m_CONF_DIR=$m_ROOT/conf
-m_LANG_DIR=$m_ROOT/lang
-
-# export vars
-export -- \
-  m_BIN_DIR \
-  m_BIN_SYS_DIR \
-  m_BIN_SYS_OSARCH_DIR \
-  m_BIN_EXT_DIR \
-  m_BIN_EXT_OSARCH_DIR \
-  m_LIB_DIR \
-  m_CONF_DIR \
-  m_LANG_DIR
-
-readonly -- \
-  m_BIN_DIR \
-  m_BIN_SYS_DIR \
-  m_BIN_SYS_OSARCH_DIR \
-  m_BIN_EXT_DIR \
-  m_BIN_EXT_OSARCH_DIR \
-  m_LIB_DIR \
-  m_CONF_DIR \
-  m_LANG_DIR
-
-# set path
-PATH=$m_BIN_SYS_OSARCH_DIR:$m_BIN_SYS_DIR:$m_BIN_EXT_OSARCH_DIR:$m_BIN_EXT_DIR${PATH:+:$PATH}
-
-# export path
-export -- PATH
-
-#-------------------------------------------------------------------------------
-# TEXT
-#-------------------------------------------------------------------------------
-
-# functions
 is_integer()
 {
   [ "$#" -eq 1 ] || return 1
@@ -174,6 +108,66 @@ text_safe_id_case()
 
   return 0
 }
+
+#-------------------------------------------------------------------------------
+# ROOT RESOLUTION
+#-------------------------------------------------------------------------------
+
+# canonicalize the path of this script and check that it is really a file
+readpathce "m_BOOTSTRAP_BIN" "$0" && [ -f "$m_BOOTSTRAP_BIN" ] || fatal 'bootstrap bin resolution error'
+
+# extract root
+m_ROOT=${m_BOOTSTRAP_BIN%/*}
+[ -n "$m_ROOT" ] || m_ROOT=/
+
+# check can cd into it
+(cd -- "$m_ROOT" 2>/dev/null) || fatal 'bootstrap dir error'
+
+# export root
+export -- m_BOOTSTRAP_BIN m_ROOT
+
+readonly -- m_BOOTSTRAP_BIN m_ROOT
+
+#-------------------------------------------------------------------------------
+# SYSTEM DIRECTORIES AND PATH
+#-------------------------------------------------------------------------------
+
+# set values
+m_BIN_DIR=$m_ROOT/bin
+m_BIN_SYS_DIR=$m_BIN_DIR/sys
+m_BIN_SYS_OSARCH_DIR=$m_BIN_DIR/sys-osarch
+m_BIN_EXT_DIR=$m_ROOT/bin/ext
+m_BIN_EXT_OSARCH_DIR=$m_ROOT/bin/ext-osarch
+m_LIB_DIR=$m_ROOT/lib
+m_CONF_DIR=$m_ROOT/conf
+m_LANG_DIR=$m_ROOT/lang
+
+# export vars
+export -- \
+  m_BIN_DIR \
+  m_BIN_SYS_DIR \
+  m_BIN_SYS_OSARCH_DIR \
+  m_BIN_EXT_DIR \
+  m_BIN_EXT_OSARCH_DIR \
+  m_LIB_DIR \
+  m_CONF_DIR \
+  m_LANG_DIR
+
+readonly -- \
+  m_BIN_DIR \
+  m_BIN_SYS_DIR \
+  m_BIN_SYS_OSARCH_DIR \
+  m_BIN_EXT_DIR \
+  m_BIN_EXT_OSARCH_DIR \
+  m_LIB_DIR \
+  m_CONF_DIR \
+  m_LANG_DIR
+
+# set path
+PATH=$m_BIN_SYS_OSARCH_DIR:$m_BIN_SYS_DIR:$m_BIN_EXT_OSARCH_DIR:$m_BIN_EXT_DIR${PATH:+:$PATH}
+
+# export path
+export -- PATH
 
 #-------------------------------------------------------------------------------
 # LANG
@@ -336,7 +330,7 @@ log()
 
 fatal()
 {
-  case "$1" in *[!0-9]* | "") EXIT_CODE="1";; *) EXIT_CODE="$1"; shift;; esac
+  case "$1" in *[!0-9]* | "") EXIT_CODE="1";; *) EXIT_CODE="$1"; shift; [ "$EXIT_CODE" -gt "255" ] && EXIT_CODE="1";; esac
 
   log fatal "$@"
 
