optimized

diff --git a/rumiai-os b/rumiai-os
--- a/rumiai-os
+++ b/rumiai-os
@@ -175,88 +175,83 @@ lang()
 : "${m_LOG_LEVEL:=info}"
 
 log()
-(
-  [ "$#" -ge 3 ] || return 1
+{
+  (
+    [ "$#" -ge 3 ] || exit 1
 
-  log_severity="$1"
-  shift
+    log_severity="$1"
+    shift
 
-  case "$log_severity" in
-    fatal) log_priority=1;;
-    error) log_priority=2;;
-    warn) log_priority=3;;
-    info) log_priority=4;;
-    debug) log_priority=5;;
-    trace) log_priority=6;;
-    *) return 2;;
-  esac
+    case "$log_severity" in
+      fatal) log_priority=1;;
+      error) log_priority=2;;
+      warn) log_priority=3;;
+      info) log_priority=4;;
+      debug) log_priority=5;;
+      trace) log_priority=6;;
+      *) exit 2;;
+    esac
 
-  case "$m_LOG_LEVEL" in
-    off | none) log_threshold="0";;
-    fatal) log_threshold="1";;
-    error) log_threshold="2";;
-    warn) log_threshold="3";;
-    info) log_threshold="4";;
-    debug) log_threshold="5";;
-    trace | all) log_threshold="6";;
-    *) return 6;;
-  esac
+    case "$m_LOG_LEVEL" in
+      off | none) log_threshold="0";;
+      fatal) log_threshold="1";;
+      error) log_threshold="2";;
+      warn) log_threshold="3";;
+      info) log_threshold="4";;
+      debug) log_threshold="5";;
+      trace | all) log_threshold="6";;
+      *) exit 3;;
+    esac
 
-  [ "$log_priority" -le "$log_threshold" ] || return 0
+    [ "$log_priority" -le "$log_threshold" ] || exit 0
 
-# text_safe_id()
-# {
-#   [ "$#" -eq 1 ] || return 1
-#
-#   case "$1" in
-#     # first character match
-#     [a-z0-9]*)
-#       # middle characters and final character exclusions
-#       case $1 in
-#         *[!a-z0-9._-]* | *[._-])
-#           return 1
-#           ;;
-#       esac
-#       ;;
-#     *)
-#       return 1
-#       ;;
-#   esac
-#
-#   return 0
-# }
-  case "$1" in "" | [!a-z0-9]* | *[!a-z0-9._-]* | *[._-]) return 2 ;; esac
-  case "$2" in "" | [!a-z0-9]* | *[!a-z0-9._-]* | *[._-]) return 2 ;; esac
+    case "$1" in "" | [!a-z0-9]* | *[!a-z0-9._-]* | *[._-]) exit 4 ;; esac
+    case "$2" in "" | [!a-z0-9]* | *[!a-z0-9._-]* | *[._-]) exit 5 ;; esac
 
-  log_domain=$1
-  log_message_id=$2
-  shift 2
-
-  log_message=$(lang "$log_domain" "$log_message_id") || log_message=$log_domain.$log_message_id
-  log_timestamp=$(command -p -- date '+%Y-%m-%dT%H:%M:%S' 2>/dev/null) || log_timestamp=-
-
-  printf -- '[%s] [%s] [%s.%s] %s' \
-    "$log_timestamp" \
-    "$log_severity" \
-    "$log_domain" \
-    "$log_message_id" \
-    "$log_message" >&2
-
-  [ "$(( $# % 2 ))" -eq 0 ] || return 3
-  while [ "$#" -gt 0 ]
-  do
-    case "$1" in "" | [!a-z0-9]* | *[!a-z0-9._-]* | *[._-]) printf -- '\n' >&2; return 4 ;; esac
-    log_field_name=$1
-    log_field_value=$2
+    log_domain=$1
+    log_message_id=$2
     shift 2
 
-    printf -- ' [%s="%s"]' \
-      "$log_field_name" \
-      "$log_field_value" >&2
-  done
+    log_message=$(lang "$log_domain" "$log_message_id") || log_message=$log_domain.$log_message_id
+    log_timestamp=$(command -p -- date '+%Y-%m-%d|%H:%M:%S' 2>/dev/null) || log_timestamp=-
 
-  printf -- '\n' >&2
-)
+    printf -- '[%s] [%s] [%s.%s] %s' \
+      "$log_timestamp" \
+      "$log_severity" \
+      "$log_domain" \
+      "$log_message_id" \
+      "$log_message" >&2
+
+    [ "$(( $# % 2 ))" -eq 0 ] || exit 6
+
+    while [ "$#" -gt 0 ]
+    do
+      case "$1" in "" | [!a-z0-9]* | *[!a-z0-9._-]* | *[._-]) printf -- '\n' >&2; exit 7 ;; esac
+      log_field_name=$1
+      log_field_value=$2
+      shift 2
+
+      printf -- ' [%s="%s"]' \
+        "$log_field_name" \
+        "$log_field_value" >&2
+    done
+
+    printf -- '\n' >&2
+  )
+
+  case "$?" in
+    "0") :;;
+    "1") printf -- '%s ' "[log] invalid number of arguments: $@" >&2; printf -- '\n' >&2;;
+    "2") printf -- '%s ' "[log] invalid log severity: $@" >&2; printf -- '\n' >&2;;
+    "3") printf -- '%s ' "[log] invalid m_LOG_LEVEL: $@" >&2; printf -- '\n' >&2;;
+    "4") printf -- '%s ' "[log] invalid log domain: $@" >&2; printf -- '\n' >&2;;
+    "5") printf -- '%s ' "[log] invalid log message id: $@" >&2; printf -- '\n' >&2;;
+    "6") printf -- '%s ' "[log] invalid parity check of <field, value> pairs: $@" >&2; printf -- '\n' >&2;;
+    "7") printf -- '%s ' "[log] invalid field name: $@" >&2; printf -- '\n' >&2;;
+    *) :;;
+  esac
+
+}
 
 #-------------------------------------------------------------------------------
 # EXECUTE
